main.js, src/app.html, src/css/main.css, src/js/app.js, src/js/functions.js, src/js/routes.js, src/views/build/global.js, src/views/build/libraryList.js, src/views/build/settings.js, src/views/global.jsx
Was supposed to be a major refactoring, but was too lazy for this one. Later. Maybe.
=> Starting to make things readable

README.md, ROADMAP.md, build.js, package.json, src/js/components/Library/Library.react.js, src/js/components/Library/TracksList.react.js, src/styles/main.scss, src/styles/themes/theme-dark.scss
=> Tracks are now grouped in tiles, render time considerably improved (#57)

README.md
Forgot to update Readme in #94
=> Update readme to drop bower

README.md, package.json
Adds compile:ci command to be used in CI along with compile for local usage.
=> Add compile:ci to npm scripts

src/js/actions/SettingsActions.js, src/js/components/Settings/SettingsAbout.react.js, src/js/components/Settings/SettingsLibrary.react.js, src/js/components/Settings/SettingsUI.react.js
My first pull request here on GitHub so if I'm doing it wrong or if there is anything I can do better please feel free to criticize and point me in the right direction.
This pull request just addresses a couple spelling and grammar issues that I found while using Museeks, nothing too much.
=> Grammar and spelling fixes

src/js/actions/PlayerActions.js, src/js/components/Header/Header.react.js, src/js/lib/player.js
poke @YurySolovyov: can you review it ?
Refs: #156
=> More natural volume + fix wrong volume on startup (fix #156)

src/js/components/Header/ButtonRepeat.react.js, src/js/components/Header/ButtonShuffle.react.js, src/js/components/Header/Header.react.js, src/js/components/Header/PlayingBar.react.js, src/js/components/Header/TrackCover.react.js, src/js/utils/utils.js, src/styles/_header.scss, src/styles/themes/theme-dark.scss
This adds basic album cover support:
- The image is stored as base64 in the database
- Covers are track-specific, not album-specific
=> Light cover support

package.json, src/js/components/Header/ButtonRepeat.react.js, src/js/components/Header/ButtonShuffle.react.js, src/js/components/Header/Header.react.js, src/js/components/Header/PlayingBar.react.js, src/js/components/Header/Queue.react.js, src/js/components/Library/Library.react.js, src/js/components/Notifications/Notifications.react.js, src/js/components/Playlists/Playlist.react.js, src/js/components/Playlists/Playlists.react.js, src/js/components/Playlists/PlaylistsNav.react.js, src/js/components/Settings/SettingsLibrary.react.js, src/js/components/Settings/SettingsUI.react.js, src/js/components/Shared/TracksList.react.js
=> Use classnames module to deal with dynamic className values

package.json, src/js/utils/utils.js
=> Fix wrong duration and wav errors

src/js/actions/AppActions.js, src/js/actions/SettingsActions.js, src/js/components/App.react.js, src/js/components/Header/Header.react.js, src/js/components/Settings/SettingsUI.react.js, src/main-process/config.js, src/main-process/ipc.js, src/main-process/main.js
=> 153 native frame option

src/js/actions/LibraryActions.js, src/js/lib/app.js
=> Do filtering of supported file extension on our own

src/js/actions/SettingsActions.js
=> Use .fetch API and .find in update-checking code

README.md, src/js/actions/LibraryActions.js, src/js/components/App.react.js, src/js/components/Header/Header.react.js, src/js/components/Header/PlayingBar.react.js, src/js/components/Header/TrackCover.react.js, src/js/components/Notifications/Notification.react.js, src/js/components/Playlists/Playlist.react.js, src/js/components/Shared/TrackRow.react.js, src/js/constants/AppConstants.js, src/js/reducers/initial-state.js, src/js/reducers/reducers.js, src/js/utils/utils.js
- Fix #191: Decent cover support
- Fix #166: Look for covers in current track directory
=> Decent covers implementation

src/js/components/Shared/TrackRow.react.js, src/js/components/Shared/TracksList.react.js, src/main-process/ipc.js
Code explication is commented when needed.
=> Easy access to an artist/album with a right click on track

src/js/components/Header/QueueList.react.js, src/js/components/Header/QueueListItem.react.js, src/styles/_header.scss, src/styles/themes/theme-dark.scss
fix #209 
- More fluid and trackable drag&drop system
- Fix drop on higher position in the list
- Style update: easier to manage drag/dragover actions
@YurySolovyov, about the review: just review the code itself, not the system, I prefered not to implement react-dnd for now, no time for that.
=> Rewrite queue drag&drop

src/main-process/ipc.js
I was looking for that :)
Downloaded some album twice, wanted to delete some old musics, here is a command to open the folder directly on the music.
Don't hesitate to say it if I made a mistake
=> Add open music folder option on right click

README.md
Because well, seems stupid only when you know it
=> Add precisions for developers on README

src/js/actions/LibraryActions.js
=> Lower fsConcurrency

src/js/actions/AppActions.js, src/main-process/main.js, src/main-process/tray.js
=> Always show tray, tray>quit quits entire app

src/js/actions/AppActions.js
=> Fix mediakeys

.babelrc, package.json, src/js/actions/SettingsActions.js
This is a simple one just to the async/await in our build pipeline, I'll do more on follow-ups
Ref: #269
=> Start using async/await for checking updates

src/js/actions/AppActions.js, src/js/lib/player.js, src/js/utils/utils.js, src/main-process/tray.js
#264 This was harder than I thought, but I finally got it. 😌
=> Display track metadata in tray

src/js/components/Shared/TracksList.react.js
Mostly, I broke a few really large methods into smaller methods.
I also want to note that [this switch](https://github.com/KeitIG/museeks/blob/master/src/js/components/Shared/TracksList.react.js#L217-L282) only really needs the default case, because the other two are covered by the default.
=> Refactor Tracklist

src/js/actions/LibraryActions.js, src/js/utils/utils.js
- Moved functions from monolith object to closure
- Split up metadata fetching for `.wav` and non-`.wav`
- Added functions to get default metadata and lowered metadata.
- Obviously introduced async/await for some complex stuff.
Refs #269
=> Use async/await in utils.js

src/js/actions/AppActions.js
=> Show new playing track notification only when the main window is not focused

src/js/actions/AppActions.js, src/main-process/ipc.js
Fix #238 
Tell me if I'm wrong but we don't need it anymore as we always show the tray (poke @dkniffin)
=> Remove onbeforeunload handler

src/js/actions/AppActions.js, src/js/actions/NotificationActions.js, src/js/actions/SettingsActions.js, src/js/components/Settings/SettingsUI.react.js, src/main-process/config.js
=> Add a setting to disable notifications

src/js/actions/AppActions.js, src/js/actions/LibraryActions.js, src/js/actions/PlaylistsActions.js, src/js/actions/QueueActions.js, src/js/components/Shared/TracksList.react.js, src/js/lib/app.js
Refs: #269 
Filed an issue about Cursor Promisification: https://github.com/Ivshti/linvodb3/issues/58
=> Use async/await with DB models

src/js/components/App.react.js, src/js/components/Library/Library.react.js, src/js/components/Playlists/Playlist.react.js, src/js/components/Playlists/Playlists.react.js, src/js/components/Shared/TracksList.react.js, src/main-process/ipc.js
=> Remove add 'to queue' from context menu if playerStatus is pause

src/js/lib/app.js
=> Add Opus extensions

src/js/actions/AppActions.js, src/js/actions/LibraryActions.js, src/js/actions/PlayerActions.js, src/js/actions/QueueActions.js, src/js/components/Header/PlayingBar.react.js, src/js/components/Header/QueueListItem.react.js, src/js/components/Header/VolumeControl.react.js, src/js/components/Settings/SettingsAbout.react.js, src/js/components/Shared/ExternalLink.react.js, src/js/components/Shared/TrackRow.react.js, src/js/components/Shared/TracksList.react.js, src/js/constants/AppConstants.js, src/js/lib/player.js, src/js/reducers/library.js, src/js/reducers/player.js, src/js/reducers/queue.js
This should close #271, I migrated the calls, now need to make it behave correct.
Posting here to track progress and to make review easier for everyone, including myself
=> Do not use Player inside reducers

.eslintrc, src/js/components/Shared/TracksList.react.js
=> Fix up, down, and enter keys in tracklist

package.json, webpack.config.js
=> Use dedupe webpack plugin

.circleci/config.yml, .travis.yml
Just wanted to play with circle CI. Build and tests done in 47 seconds. 
It's something.
=> Replace Travis by Circle CI 2.0

src/js/actions/PlayerActions.js
Didn't really think this would be that easy.
fix #223 
fix #226
=> Play automatically plays the first song when the player is stopped

src/js/components/Shared/TracksList.react.js
=> Fix PageDown, PageUp, End and Start keys on TracksList

src/ui/actions/NotificationActions.js
=> When songs are skipped, the notification gets updated. Fixes #358

.circleci/config.yml, package.json
Just a trick to reduce CircleCI time by 50%.
=> Circleci cache

src/ui/components/App.react.js, src/ui/components/Header/QueueList.react.js, src/ui/components/Header/QueueListItem.react.js, src/ui/components/Header/VolumeControl.react.js, src/ui/components/Playlists/PlaylistsNav.react.js, src/ui/components/Settings/SettingsLibrary.react.js, src/ui/components/Shared/TracksList.react.js, src/ui/styles/_header.scss, src/ui/styles/_view-common.scss, src/ui/styles/_view-library.scss, src/ui/styles/_view-playlists.scss, src/ui/styles/themes/theme-dark.scss
- Use flex instead of CSS's `calc()` everywhere possible 
- Remove some useless brackets
=> Minor code improvements

package-lock.json, package.json, src/ui/components/Header/PlayingBar.react.js, src/ui/components/Header/PlayingBarInfos.react.js, src/ui/components/Header/QueueListItem.react.js, src/ui/styles/_view-common.scss
I removed the unwanted commits 
---
Still not perfect, but we're getting there.
Before: 
After:
For the record, when removing completely the animation:
=> Better CPU usage 2

src/ui/actions/LibraryActions.js, src/ui/actions/PlayerActions.js, src/ui/components/Footer/Footer.react.js, src/ui/components/Header/QueueList.react.js, src/ui/components/Library/Library.react.js, src/ui/components/Playlists/Playlist.react.js, src/ui/components/Playlists/Playlists.react.js, src/ui/components/Shared/TrackRow.react.js, src/ui/components/Shared/TracksList.react.js, src/ui/constants/action-types.js, src/ui/reducers/library.js, src/ui/utils/utils-library.js, src/ui/utils/utils.js
Fix #372 
Needed for #62 
I did not notice any jank/performance loss, which is 🎉 . I needed to fix some functions though, like the status in the footer, and when you start playing a video from TracksList.
=> Simpler library reducer

src/ui/actions/PlayerActions.js, src/ui/reducers/player.js
=> Fix shuffle rollback

package-lock.json, package.json, src/shared/types/interfaces.ts, src/ui/actions/AppActions.ts, src/ui/actions/LibraryActions.ts, src/ui/actions/PlaylistsActions.ts, src/ui/components/PlaylistsNav/PlaylistsNav.tsx, src/ui/components/Setting/Setting.css, src/ui/components/Setting/Setting.tsx, src/ui/components/SettingDropzone/SettingDropzone.css, src/ui/components/TracksList/TracksList.tsx, src/ui/elements/ExternalLink/ExternalLink.css, src/ui/lib/app.ts, src/ui/utils/utils-m3u.ts, src/ui/views/Playlists/Playlists.tsx, src/ui/views/Settings/Settings.css, src/ui/views/Settings/SettingsAbout.tsx, src/ui/views/Settings/SettingsLibrary.tsx, webpack.common.js
=> m3u support

src/main/modules/config.ts, src/shared/types/interfaces.ts, src/ui/actions/AppActions.ts, src/ui/actions/PlayerActions.ts, src/ui/components/AudioOutputSelect/AudioOutputSelect.tsx, src/ui/components/Setting/Setting.css, src/ui/components/Setting/Setting.tsx, src/ui/lib/player.ts, src/ui/views/Settings/SettingsAudio.tsx
=> Add custom audio output feature

package-lock.json, package.json, src/main/modules/ipc.ts, src/main/modules/sleep-blocker.ts, src/main/modules/tray.ts, src/shared/types/definitions/ps-node.d.ts, src/ui/components/Cover/Cover.css, src/ui/components/PlaylistsNav/PlaylistsNav.css, src/ui/components/Setting/Setting.css, src/ui/components/SettingCheckbox/SettingCheckbox.css, src/ui/elements/Button/Button.css, src/ui/main.tsx, src/ui/styles/general.css, src/ui/styles/themes/dark.json, src/ui/styles/themes/light.json, src/ui/utils/utils.ts, src/ui/views/Settings/SettingsUI.tsx
The work is not completely done on Linux, but 90% of the job is done.
=> Tray improvements

src/ui/components/TracksList/TracksList.tsx
Branch name is wrong, this is implementing #489 plus CTRL+A support. 
To reviewer: Similar to #496 please name and shame any mistakes so I can learn!
=> Adding CTRL+A plus shift as a modifier (#489)

src/ui/actions/PlaylistsActions.ts, src/ui/components/PlaylistsNavLink/PlaylistsNavLink.tsx
#495
I'm pretty new to both React and the whole git system, please let me know if anything here is less-than-ideal
=> Adding Double Click to play (#495)

src/ui/components/TracksList/TracksList.tsx
=> Fixing empty playlist on context menu create

src/ui/components/TracksList/TracksList.tsx
Use headerStyles for search input in querySelector
=> Fixes quick search for album or artist in right click menu

src/ui/views/Settings/SettingsAudio.tsx
=> use parseFloat instead of parseInt

package-lock.json, package.json
Solves a couple issues I was experiencing personally:
https://github.com/Borewit/music-metadata/issues/388
https://github.com/Borewit/music-metadata/issues/387
=> bump mmd to 6.3.4

.github/workflows/build.yml, electron-builder.yml, src/renderer/styles/themes/dark.json
- Fixes #587
- Fixes ia32 windows binaries not created (🙈)
=> Portable win32 binaries

src/renderer/App.tsx
=> Add shortcuts for library and playlists views

electron-builder.yml
Works locally, does it work on GH Actions now?
Fixes #572
=> Add support for M1 binaries

src/renderer/lib/player.ts, src/renderer/store/actions/PlayerActions.ts, src/renderer/store/actions/QueueActions.ts, src/renderer/store/store.ts
Fixed #624
/147424480-7d9fd66e-2d9b-4217-a5a9-d94dfaeb67ff.png">
I might be an easier way to integrate with mpris as well
=> Media Session

.github/workflows/build.yml, electron-builder.yml
- Adds platform infix like `win`, `linux` and `macos`.
- Added `tar.gz` target in linux.
=> Better built executable naming

src/main/entrypoint.ts, src/preload/db.ts, src/preload/entrypoint.ts, src/renderer/components/Events/GlobalKeyBindings.tsx, src/renderer/components/Events/IPCPlayerEvents.tsx, src/renderer/components/Events/MediaSessionEvents.tsx, src/renderer/components/Events/PlayerEvents.tsx, src/renderer/components/PlayingBarInfo/PlayingBarInfo.tsx, src/renderer/components/PlaylistsNav/PlaylistsNav.tsx, src/renderer/components/TracksList/TracksList.tsx, src/renderer/components/VolumeControl/VolumeControl.tsx, src/renderer/lib/player.ts, src/renderer/stores/AppAPI.ts, src/renderer/stores/usePlayerStore.ts
It only took years. And I'm not even sure it works. And It's not even completely secure.
=> Disable nodeIntegration + enable contextIsolation

src/renderer/components/Queue/Queue.tsx, src/renderer/components/QueueList/QueueList.tsx, src/renderer/components/QueueListItem/QueueListItem.module.css, src/renderer/elements/Button/Button.module.css, src/renderer/elements/Button/Button.tsx
=> See more queue

src/renderer/components/SettingCheckbox/SettingCheckbox.module.css, src/shared/themes/dark.json
The new dark theme was a good addition, but it was too bluey. This is an attempt to solve that.
=> Dark Theme Update

electron-builder.yml
=> Fix: module not found in package

src/renderer/components/PlayerControls/PlayerControls.module.css, src/renderer/elements/Button/Button.module.css
Just a small contribution for make button cursor pointer :)
=> Feat: Make click element cursor pointer

src/renderer/hooks/useCurrentViewTracks.ts, src/renderer/views/Library/Library.tsx, src/renderer/views/Playlists/Playlist.tsx, src/renderer/views/Playlists/Playlists.tsx, src/renderer/views/Root.tsx, src/renderer/views/Settings/Settings.tsx, src/renderer/views/Settings/SettingsAudio.tsx, src/renderer/views/Settings/SettingsUI.tsx, src/renderer/views/router.tsx
Move each loader closer to their route component
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/martpie/museeks/pull/706).
* #707
* __->__ #706
=> Move each loader closer to their route component

src/renderer/components/Header/Header.module.css, src/renderer/components/PlayingBar/PlayingBar.module.css, src/renderer/components/PlayingBarInfo/PlayingBarInfo.module.css, src/renderer/components/PlayingBarInfo/PlayingBarInfo.tsx, src/renderer/components/TrackProgress/TrackProgress.module.css, src/renderer/components/TrackProgress/TrackProgress.tsx, src/renderer/components/VolumeControl/VolumeControl.module.css, src/renderer/hooks/usePlayingTrack.ts, src/renderer/hooks/usePlayingTrackCurrentTime.ts, src/renderer/hooks/usePlayingTrackID.ts, src/renderer/views/Library/Library.tsx, src/renderer/views/Playlists/Playlist.tsx
Extract track progress in separate component + new player hooks
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/martpie/museeks/pull/712).
* #715
* #714
* #713
* __->__ #712
=> Extract track progress in separate component + new player hooks

src/renderer/components/ProgressBar/ProgressBar.module.css, src/renderer/components/Setting/Setting.module.css, src/renderer/components/TrackProgress/TrackProgress.module.css, src/renderer/components/TrackRow/TrackRow.module.css, src/renderer/components/VolumeControl/VolumeControl.module.css, src/renderer/elements/Button/Button.module.css
Add active styles on buttons
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/martpie/museeks/pull/715).
* __->__ #715
* #714
* #713
=> Add active styles on buttons

package.json, src/main/modules/ConfigModule.ts, src/renderer/components/TracksList/TracksList.tsx, src/renderer/stores/SettingsAPI.ts, src/renderer/views/Library/Library.tsx, src/renderer/views/Playlists/Playlist.tsx, src/renderer/views/Settings/SettingsUI.tsx, src/shared/types/museeks.ts
Add compact mode for tracks list
=> Add compact mode for tracks list

src/renderer/elements/Button/Button.module.css, src/renderer/elements/ExternalLink/ExternalLink.module.css
Text accessibility improvements
=> Text accessibility improvements

src/main/lib/utils-cover.ts, src/main/modules/NativeThemeModule.ts, src/main/modules/SleepBlockerModule.ts, src/renderer/components/AudioOutputSelect/AudioOutputSelect.tsx, src/renderer/components/PlaylistsNav/PlaylistsNav.tsx, src/renderer/components/PlaylistsNavLink/PlaylistsNavLink.tsx, src/renderer/components/TrackRow/TrackRow.tsx, src/renderer/components/TracksList/TracksList.tsx, src/renderer/lib/player.ts, src/renderer/stores/PlaylistsAPI.ts, src/renderer/stores/SettingsAPI.ts, src/renderer/stores/useLibraryStore.ts, src/renderer/stores/usePlayerStore.ts, src/renderer/views/Details/Details.tsx, src/renderer/views/Library/Library.tsx, src/renderer/views/Playlists/Playlist.tsx, src/renderer/views/Playlists/Playlists.tsx, src/renderer/views/router.tsx, src/shared/lib/__tests__/themes.test.ts, src/shared/themes/light.json, src/shared/types/museeks.ts
=> Consistent ID naming

src/components/TracksList/TracksList.tsx, src/hooks/useScrollRestoration.ts
=> Scroll Restoration between Views

src-tauri/Info.plist, src-tauri/src/libs/events.rs, src-tauri/src/libs/file_associations.rs, src-tauri/src/libs/mod.rs, src-tauri/src/libs/track.rs, src-tauri/src/libs/utils.rs, src-tauri/src/main.rs, src-tauri/src/plugins/database.rs, src-tauri/tauri.conf.json, src/components/Events/IPCPlayerEvents.tsx, src/generated/typings/index.ts
=> File associations

.github/workflows/build.yml
=> Fix binaries not being uploaded during CI

src/components/Setting.module.css, src/components/Setting.tsx, src/stores/useLibraryStore.ts, src/types/museeks.ts, src/views/ViewTrackDetails.tsx
Replaces #791 
Kinda impersonated @igorer88 for the commit, but I hope you don't mind.
=> Edit more ID3 tags (#732)

.github/workflows/build.yml, scripts/gen.sh
=> Fix GLIBC issues

src/components/TracksList.tsx, src/routes/library.tsx, src/routes/playlists.$playlistID.tsx
I don't want to copy-paste the whole tracks selection logic on the default view and the artists view. This requires making TracksList layout and virtualizer agnostic.
=> Artists View - Prework

src/components/Footer.tsx, src/components/IPCNavigationEvents.tsx, src/components/IPCPlayerEvents.tsx, src/components/TracksList.tsx, src/main.tsx, src/routes/__root.tsx, src/routes/playlists.$playlistID.tsx, src/routes/playlists.tsx, src/stores/PlaylistsAPI.ts, src/stores/usePlayerStore.ts, src/types/museeks.ts
- Fix #738
- Prefetch data on hover
=> Faster navigation

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src/components/IPCNavigationEvents.tsx, src/components/MediaSessionEvents.tsx
=> Temporary fix for Keybindings on Linux + Windows

package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/release/io.museeks.app.yaml, src-tauri/tauri.conf.json, src/components/SideNavLink.module.css, src/components/SideNavLink.tsx, src/routes/artists.tsx, src/routes/playlists.tsx, src/translations/en.po, src/translations/fr.po
=> Fix "not found" error with playlists/artists with "/" in their names 

.github/workflows/build.yml, src/components/SideNav.module.css, src/components/SideNav.tsx, src/components/SideNavLink.tsx, src/translations/en.po, src/translations/fr.po, src/translations/ru.po
=> Add first-letter indicators to side nav

src/translations/languages.ts, src/translations/zh-TW.po
As description, add the traditional chinese for translation
=> feat: support to translate in traditional chinese
